name: Build and Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build
        run: |
          npm install
          npm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./build/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build
          path: ./build/

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Clear AWS S3
        run: |
          aws s3 rm s3://${{ secrets.BUCKET }} --recursive

      - name: Upload .html Without Extension
        run: |
          find ./build -type f -name "*.html" | \
          xargs -I {} aws s3 cp "{}" "s3://${{ secrets.BUCKET }}/$(basename {} .html)" \
          --content-type text/html
        shell: bash -eo pipefail

      - name: Upload Other Files
        run: |
          aws s3 sync ./build/ s3://${{ secrets.BUCKET }} --exclude "*.html"

      - name: Clear CDN Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.DIST_ID }} \
            --paths "/**/*"
