name: Build and Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout

      - name: Build
        run: |
          npm install
          npm run build

      - name: Clean
        run: |
          find ./build -type f -name "*.html" | xargs -I {} bash -c 'mv "$0" "${0%.html}"' {}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact
        with:
          name: build-artifacts
          path: ./build/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact
        with:
          name: build-artifacts

      - name: Print Build Artifacts
        run: |
          ls -l build-artifacts/

      # - name: Configure AWS
      #   uses: aws-actions/configure-aws-credentials
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_REGION }}
      #
      # - name: Upload to AWS
      #
      # - name: Clear CDN Cache
      #   run: |
      #     aws cloudfront create-invalidation \
      #       --distribution-id ${{ secrets.DIST_ID }} \
      #       --paths "/**/*"
